version: "3.5"

services:

  # -------------------------------------------------------
  # NATS CLUSTER | a p2p network using seeding (port 6222)
  # -------------------------------------------------------
  nats-1:
    image: "nats:1.3.0"
    container_name: nats001
    command: -p 4222 -m 8222 -cluster nats://172.25.255.10:6222 -auth S3Cr3T0k3n!
    image: "nats:1.3.0"
    networks: 
      chainet: 
        ipv4_address: "172.25.255.10"

  nats-2:
    image: "nats:1.3.0"
    container_name: nats002
    command: -p 4222 -m 8222 -cluster nats://172.25.255.11:6222 -routes nats://172.25.255.10:6222 -auth S3Cr3T0k3n!
    expose:
      - "6222"
    networks: 
      chainet: 
        ipv4_address: "172.25.255.11"

  nats-3:
    image: "nats:1.3.0"
    container_name: nats003
    command: -p 4222 -m 8222 -cluster nats://172.25.255.12:6222 -routes nats://172.25.255.10:6222 -auth S3Cr3T0k3n!
    expose:
      - "6222"
    networks: 
      chainet: 
        ipv4_address: "172.25.255.12"

  mongo001:
    image: mongo
    container_name: mongo001
    restart: always
    networks:
      chainet:
        ipv4_address: "172.25.255.20"

  mongo002:
    image: mongo
    container_name: mongo002
    restart: always
    networks:
      chainet:
        ipv4_address: "172.25.255.21"

  mongo003:
    image: mongo
    container_name: mongo003
    restart: always
    networks:
      chainet:
        ipv4_address: "172.25.255.22"

  nodejs:
    image: node:10.12
    container_name: nodejs
    user: "1000:1000"
    volumes:
      - ../:/app
    command: tail -f /dev/null
    working_dir: /app
    depends_on:
      - nats-1
      - nats-2
      - nats-3
      - mongo001
      - mongo002
      - mongo003
      - jaeger
    networks:
      chainet:
        ipv4_address: "172.25.255.30"

  jaeger:
    # https://www.jaegertracing.io/docs/1.6/getting-started/#all-in-one-docker-image
    # http://jaeger:16686
    image: jaegertracing/all-in-one:1.7
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks: 
      chainet: 
        ipv4_address: "172.25.255.40"

networks:
  chainet:
    name: chainet
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.255.0/24
