version: "3.5"

services:

  # redis:
  #   image: redis
  #   container_name: redis
  #   volumes:
  #     - ./data/redis:/data
  #   networks:
  #     chainet:
  #       ipv4_address: "172.25.255.30"

  jaeger:
    # https://www.jaegertracing.io/docs/1.6/getting-started/#all-in-one-docker-image
    # http://jaeger:16686
    image: jaegertracing/all-in-one:1.7
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks: 
      chainet: 
        ipv4_address: "172.25.255.40"

  nodejs:
    image: node:10.12
    container_name: nodejs
    user: "1000:1000"
    volumes:
      - ../:/app
    command: tail -f /dev/null
    working_dir: /app
    depends_on:
      - nats-1
      - nats-2
      - nats-3
      - mongo001
      - mongo002
      - mongo003
      - jaeger
    networks:
      chainet:
        ipv4_address: "172.25.255.50"
