version: "3.5"

services:

  # -------------------------------------------------------
  # Application peers for integration tests
  # -------------------------------------------------------
  nodejs:
    image: node:10.12
    container_name: nodejs
    user: "1000:1000"
    volumes:
      - ../:/app
    command: tail -f /dev/null
    working_dir: /app
    depends_on:
      - nats-1
      - nats-2
      - nats-3
      - mongo001
      - mongo002
      - mongo003
      - jaeger
    networks:
      chainet:
        ipv4_address: "172.25.255.50"
  
  peer000:
    image: node:10.12
    container_name: peer000
    user: "1000:1000"
    volumes:
      - ../:/app
    environment:
      - CONFIGS=/app/test/configs/generic.js
      - BLOCKCHAIN=blockchain
      - ROLE=blockgenerator
      - PEER_ID=000
      - DB_TYPE=mongodb
      - DB_HOST=172.25.255.20
      - WEBUI_HOST=172.25.255.51
    command: npm start
    working_dir: /app
    depends_on:
      - nodejs
    networks:
      chainet:
        ipv4_address: "172.25.255.51"

  peer001:
    image: node:10.12
    container_name: peer001
    user: "1000:1000"
    volumes:
      - ../:/app
    environment:
      - CONFIGS=/app/test/configs/generic.js
      - BLOCKCHAIN=blockchain
      - ROLE=peer
      - PEER_ID=001
      - DB_TYPE=mongodb
      - DB_HOST=172.25.255.21
      - WEBUI_HOST=172.25.255.52
    command: npm start
    working_dir: /app
    depends_on:
      - peer000
    networks:
      chainet:
        ipv4_address: "172.25.255.52"
