version: "3.5"

services:

  # -------------------------------------------------------
  # NATS CLUSTER | a p2p network using seeding (port 6222)
  # -------------------------------------------------------
  nats-1:
    image: "nats:1.3.0"
    container_name: nats001
    command: -p 4222 -m 8222 -cluster nats://172.25.255.10:6222 -auth S3Cr3T0k3n!
    image: "nats:1.3.0"
    networks: 
      chainet: 
        ipv4_address: "172.25.255.10"

  nats-2:
    image: "nats:1.3.0"
    container_name: nats002
    command: -p 4222 -m 8222 -cluster nats://172.25.255.11:6222 -routes nats://172.25.255.10:6222 -auth S3Cr3T0k3n!
    expose:
      - "6222"
    networks: 
      chainet: 
        ipv4_address: "172.25.255.11"

  nats-3:
    image: "nats:1.3.0"
    container_name: nats003
    command: -p 4222 -m 8222 -cluster nats://172.25.255.12:6222 -routes nats://172.25.255.10:6222 -auth S3Cr3T0k3n!
    expose:
      - "6222"
    networks: 
      chainet: 
        ipv4_address: "172.25.255.12"
